cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/chatbot_ai_with_speech_recognition_device_telegram_bot_documentation
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_linux
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_fucshia
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_macos
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_server
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_apis
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_android
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_ios
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_client
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_scheme
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_dart
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_assets_flutter
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_web
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_flutter
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_isar_scheme
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_cli
flutter clean

cd /home/galaxeus/Documents/private_library/general_private_tools/templates/chatbot_ai_with_speech_recognition_device_telegram_bot/package/chatbot_ai_with_speech_recognition_device_telegram_bot_windows
flutter clean

