name: 'chatbot_ai_with_speech_recognition_device_telegram_bot_project'
description: 'chatbot_ai_with_speech_recognition_device_telegram_bot is program for help you, booster up your projects significants'
version: '0.0.0'
repository: 'https://github.com/AegizTyreseValfredo/chatbot_ai_with_speech_recognition_device_telegram_bot'
homepage: 'https://github.com/AegizTyreseValfredo/chatbot_ai_with_speech_recognition_device_telegram_bot'
issue_tracker: 'https://github.com/AegizTyreseValfredo/chatbot_ai_with_speech_recognition_device_telegram_bot/issues'
documentation: 'https://github.com/AegizTyreseValfredo/chatbot_ai_with_speech_recognition_device_telegram_bot/tree/main/docs'
funding:
  - 'https://github.com/sponsors/AegizTyreseValfredo'
  - 'https://github.com/sponsors/AegizTyreseValfredo'
  - 'https://github.com/sponsors/generalfoss'
platforms:
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  general_lib: '^0.0.62'
  packagex: '^0.0.85'
  path: '^1.9.0'
  yaml: '^3.1.3'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'

