name: 'chatbot_ai_with_speech_recognition_device_telegram_bot_cli'
description: 'A sample command-line application.'
version: '0.0.0'
publish_to: 'none'
environment:
  sdk: '>=3.6.0 <4.0.0'
dependencies:
  chatbot_ai_with_speech_recognition_device_telegram_bot:
    path: '../../../package/chatbot_ai_with_speech_recognition_device_telegram_bot'
  packagex: '^0.0.85'
dev_dependencies:
  lints: '^5.0.0'
  test: 'any'
  msix: '^3.16.8'
dependency_overrides:
  pointycastle: '3.8.0'
  mime: '^2.0.0'
funding: []
packagex:
  name: 'chatbot_ai_with_speech_recognition_device_telegram_bot_cli'
  is_without_platform_name: true
  is_app_auto_clean_up_folder: true
  flutter_build_arguments:
    - '--split-per-abi'
    - '--build-name'
    - '0.0.0'
    - '--build-number'
    - '0.0.0'
    - '--obfuscate'
    - '--split-debug-info'
    - 'packagex-build-debug'
  dart_compile_exe_arguments:
    - '--save-debugging-info=packagex-compile-debug'
  uploads:
    - platform_type: 'github'
      github_username: 'AegizTyreseValfredo'
      github_tag: 'release'
      github_is_org: false
      github_repository_name: 'chatbot_ai_with_speech_recognition_device_telegram_bot'
  packages:
    - dart_target: 'chatbot_ai_with_speech_recognition_device_telegram_bot_cli'
      flutter_target: 'main'
      dart_name: 'chatbot_ai_with_speech_recognition_device_telegram_bot_cli'
      flutter_name: 'chatbot_ai_with_speech_recognition_device_telegram_bot_cli'
      output_name: 'chatbot-ai-with-speech-recognition-device-telegram-bot-cli'
msix_config:
  display_name: 'chatbot_ai_with_speech_recognition_device_telegram_bot_cli'
  install_certificate: false
