export "package_full_template_pubspec_config.dart";
export "pubspec_chatbot_ai_with_speech_recognition_device_telegram_bot.dart";
export "pubspec_chatbot_ai_with_speech_recognition_device_telegram_bot_dependencies.dart";
export "pubspec_chatbot_ai_with_speech_recognition_device_telegram_bot_dependencies_extra.dart";
export "pubspec_chatbot_ai_with_speech_recognition_device_telegram_bot_dev_dependencies.dart";
export "pubspec_chatbot_ai_with_speech_recognition_device_telegram_bot_dev_dependencies_extra.dart";
export "pubspec_chatbot_ai_with_speech_recognition_device_telegram_bot_environment.dart";
export "pubspec_chatbot_ai_with_speech_recognition_device_telegram_bot_platforms.dart";