name: Release
on: 
  workflow_dispatch:  
  push:
    branches:
      - main
    paths:
      - '.github/workflows/release.yaml'
      - 'release'
      
jobs: 
  cli-build:
    name: Cli Build
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    env:
      packagex_github_token: ${{ secrets.PACKAGEX_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 1
         submodules: true
 

      - name: Install Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
         channel: stable
         flutter-version: 3.27.0
         cache: true

      - name: Build Chatbot Ai Telegram Bot Cli
        shell: bash
        working-directory: release/clis/chatbot_ai_with_speech_recognition_device_telegram_bot_cli
        run: |
          dart pub get
          dart run packagex --command build --platform linux

      - name: Upload Release Chatbot Ai Telegram Bot Cli
        shell: bash
        working-directory: release/clis/chatbot_ai_with_speech_recognition_device_telegram_bot_cli
        run: |
          dart run packagex --command publish
          
      - name: Delete All Files
        shell: bash
        run: |
          rm -rf *
          